// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWTlAVEG8viSYmA1mbgCke0Wo-y224w0',
    appId: '1:621055862156:web:d99659628dbe0012ac62a9',
    messagingSenderId: '621055862156',
    projectId: 'bacayu-35640',
    authDomain: 'bacayu-35640.firebaseapp.com',
    storageBucket: 'bacayu-35640.firebasestorage.app',
    measurementId: 'G-QW3CFRSHTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXarsNsPYMvBYeJQxDP0etFYlTMSAJ_Ss',
    appId: '1:621055862156:android:1319800708c311f9ac62a9',
    messagingSenderId: '621055862156',
    projectId: 'bacayu-35640',
    storageBucket: 'bacayu-35640.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJ4D2Cpcr3ceF15-L3wDJOWqt9ltMV4E',
    appId: '1:621055862156:ios:46d87bebd5a8ea6aac62a9',
    messagingSenderId: '621055862156',
    projectId: 'bacayu-35640',
    storageBucket: 'bacayu-35640.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJ4D2Cpcr3ceF15-L3wDJOWqt9ltMV4E',
    appId: '1:621055862156:ios:46d87bebd5a8ea6aac62a9',
    messagingSenderId: '621055862156',
    projectId: 'bacayu-35640',
    storageBucket: 'bacayu-35640.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWTlAVEG8viSYmA1mbgCke0Wo-y224w0',
    appId: '1:621055862156:web:9d4841a0eef8dee1ac62a9',
    messagingSenderId: '621055862156',
    projectId: 'bacayu-35640',
    authDomain: 'bacayu-35640.firebaseapp.com',
    storageBucket: 'bacayu-35640.firebasestorage.app',
    measurementId: 'G-C4BLDGVRWL',
  );
}
